### ISSUE TITLE
Code refactoring.

### ISSUE THREAD

**Issue by uncle-tee** [mosesajire/pi-generator#2]
Good architecture but miniaturiseas much as you can

Why isset(_GET), you can do without it.

**Comment by mosesajire** [comment]
Thanks for your observation.

Yes, you are right. The isset($_GET...) is not necessary: isset($_POST['submit']) is already performing its function.

I have refactored the code accordingly. 

Hope it is better.

Regards.

**Comment by uncle-tee** [comment]
Nice... I think !empty($_post("submit")is not needed. Isset($_post) is already doing the needful for you.

**Comment by mosesajire** [comment]
That's right. It has been removed.
